//You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Return the letter that was added to t.

public class FindTheDifference {
    public static char findTheDifference(String s, String t) {
        int result = 0;

        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i);
        }

        for (int i = 0; i < t.length(); i++) {
            result ^= t.charAt(i);
        }

        return (char) result;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        System.out.println(findTheDifference(s, t));  // Output: e
    }
}
